### ISSUE TITLE
Console output not reporting when there's no internet connection

### ISSUE THREAD

**Issue by iingram** [conservationtechlab/cougarvision#52]
I fired up CougarVision on the WILD demo machine back in the lab just now before connecting the machine to the network and the console output appeared to merrily report image fetches and other healthy activity without calling out that there was no connection to a network (let alone the internet) and therefore no chance of actually fetching images :-)

This should be looked into and if this is the case, we need to have appropriate warning(s) in the console when the network/internet connection is missing.

**Comment by kgarwoodsdzwa** [comment]
resolved in pr #59 , loop continues to retry but outputs if there is no connection
