### ISSUE TITLE
make to work with updated pypi animl-py

### ISSUE THREAD

**Issue by kgarwoodsdzwa** [conservationtechlab/cougarvision#53]
animl-py was updated and it slightly changed some function names/locations that cougarvision calls. needs to be updated to work directly after pip installing animl

**Comment by iingram** [comment]
Obviously there's flux right now on `animl-py` as it is rapidly brought up to speed but we should work quickly to stabilize the API on `animl-py` as we have been inviting (and getting) outside users who are likely to be less tolerant of breaking API changes.   I think a good number of these breaking changes might be changing module names, function names, class names, etc. to make them PEP8 compliant (is that a correct assumption?). And that is a *really* good thing so let's welcome it. But we should get to a point soon where such changes are rarer and very deliberately made and communicated and folks working on internal projects that are dependent on `animl-py` (CougarVision might be the primary one) should communicate to the development team on `animl-py` that they are encountering breaking changes (perhaps that is already happening?) to make sure that such changes are made cautiously.
